//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.239.
// 
#pragma warning disable 1591

namespace AppSincoWord.WsArbolVariablesRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsWordArbolVariablesSoap", Namespace="http://tempuri.org/")]
    public partial class WsWordArbolVariables : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetModulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoredProceduresOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsWordArbolVariables() {
            this.Url = global::AppSincoWord.Properties.Settings.Default.AppSincoWord_WsArbolVariablesRef_WsWordArbolVariables;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTreeCompletedEventHandler GetTreeCompleted;
        
        /// <remarks/>
        public event GetModulesCompletedEventHandler GetModulesCompleted;
        
        /// <remarks/>
        public event GetStoredProceduresCompletedEventHandler GetStoredProceduresCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTree", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WordGrandPaNode GetTree(string SPName) {
            object[] results = this.Invoke("GetTree", new object[] {
                        SPName});
            return ((WordGrandPaNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetTreeAsync(string SPName) {
            this.GetTreeAsync(SPName, null);
        }
        
        /// <remarks/>
        public void GetTreeAsync(string SPName, object userState) {
            if ((this.GetTreeOperationCompleted == null)) {
                this.GetTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTreeOperationCompleted);
            }
            this.InvokeAsync("GetTree", new object[] {
                        SPName}, this.GetTreeOperationCompleted, userState);
        }
        
        private void OnGetTreeOperationCompleted(object arg) {
            if ((this.GetTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTreeCompleted(this, new GetTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetModules", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoadComboBox[] GetModules() {
            object[] results = this.Invoke("GetModules", new object[0]);
            return ((LoadComboBox[])(results[0]));
        }
        
        /// <remarks/>
        public void GetModulesAsync() {
            this.GetModulesAsync(null);
        }
        
        /// <remarks/>
        public void GetModulesAsync(object userState) {
            if ((this.GetModulesOperationCompleted == null)) {
                this.GetModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModulesOperationCompleted);
            }
            this.InvokeAsync("GetModules", new object[0], this.GetModulesOperationCompleted, userState);
        }
        
        private void OnGetModulesOperationCompleted(object arg) {
            if ((this.GetModulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModulesCompleted(this, new GetModulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoredProcedures", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoadComboBox[] GetStoredProcedures(string ModuloID) {
            object[] results = this.Invoke("GetStoredProcedures", new object[] {
                        ModuloID});
            return ((LoadComboBox[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStoredProceduresAsync(string ModuloID) {
            this.GetStoredProceduresAsync(ModuloID, null);
        }
        
        /// <remarks/>
        public void GetStoredProceduresAsync(string ModuloID, object userState) {
            if ((this.GetStoredProceduresOperationCompleted == null)) {
                this.GetStoredProceduresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoredProceduresOperationCompleted);
            }
            this.InvokeAsync("GetStoredProcedures", new object[] {
                        ModuloID}, this.GetStoredProceduresOperationCompleted, userState);
        }
        
        private void OnGetStoredProceduresOperationCompleted(object arg) {
            if ((this.GetStoredProceduresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoredProceduresCompleted(this, new GetStoredProceduresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WordGrandPaNode {
        
        private WordParentNode[] nodosPadresField;
        
        private WordSonNode[] nodosHijosField;
        
        /// <comentarios/>
        public WordParentNode[] NodosPadres {
            get {
                return this.nodosPadresField;
            }
            set {
                this.nodosPadresField = value;
            }
        }
        
        /// <comentarios/>
        public WordSonNode[] NodosHijos {
            get {
                return this.nodosHijosField;
            }
            set {
                this.nodosHijosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WordParentNode {
        
        private string cVSCodigoField;
        
        private string cVSDescripcionField;
        
        /// <comentarios/>
        public string CVSCodigo {
            get {
                return this.cVSCodigoField;
            }
            set {
                this.cVSCodigoField = value;
            }
        }
        
        /// <comentarios/>
        public string CVSDescripcion {
            get {
                return this.cVSDescripcionField;
            }
            set {
                this.cVSDescripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadComboBox {
        
        private int idField;
        
        private string descripcionField;
        
        private string auxIdField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string AuxId {
            get {
                return this.auxIdField;
            }
            set {
                this.auxIdField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WordSonNode {
        
        private string descripcionField;
        
        private string cVSDescripcionField;
        
        private string cVSCodigoField;
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string CVSDescripcion {
            get {
                return this.cVSDescripcionField;
            }
            set {
                this.cVSDescripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string CVSCodigo {
            get {
                return this.cVSCodigoField;
            }
            set {
                this.cVSCodigoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTreeCompletedEventHandler(object sender, GetTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WordGrandPaNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WordGrandPaNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetModulesCompletedEventHandler(object sender, GetModulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoadComboBox[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoadComboBox[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStoredProceduresCompletedEventHandler(object sender, GetStoredProceduresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoredProceduresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoredProceduresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoadComboBox[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoadComboBox[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591