//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace AppSincoProject.WsProjectERPref {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSProjectERPtestSoap", Namespace="http://tempuri.org/")]
    public partial class WSProjectERPtest : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetModulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveConfigsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveWeekExceptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportarErrorExternoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSProjectERPtest() {
            this.Url = global::AppSincoProject.Properties.Settings.Default.AppSincoProject_WsProjectERPref_WSProjectERPtest;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetModulesCompletedEventHandler GetModulesCompleted;
        
        /// <remarks/>
        public event GetProjectsCompletedEventHandler GetProjectsCompleted;
        
        /// <remarks/>
        public event LoadProjectCompletedEventHandler LoadProjectCompleted;
        
        /// <remarks/>
        public event SaveConfigsCompletedEventHandler SaveConfigsCompleted;
        
        /// <remarks/>
        public event SaveWeekExceptionsCompletedEventHandler SaveWeekExceptionsCompleted;
        
        /// <remarks/>
        public event SaveProjectCompletedEventHandler SaveProjectCompleted;
        
        /// <remarks/>
        public event ReportarErrorExternoCompletedEventHandler ReportarErrorExternoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetModules", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoadComboBox[] GetModules() {
            object[] results = this.Invoke("GetModules", new object[0]);
            return ((LoadComboBox[])(results[0]));
        }
        
        /// <remarks/>
        public void GetModulesAsync() {
            this.GetModulesAsync(null);
        }
        
        /// <remarks/>
        public void GetModulesAsync(object userState) {
            if ((this.GetModulesOperationCompleted == null)) {
                this.GetModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModulesOperationCompleted);
            }
            this.InvokeAsync("GetModules", new object[0], this.GetModulesOperationCompleted, userState);
        }
        
        private void OnGetModulesOperationCompleted(object arg) {
            if ((this.GetModulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModulesCompleted(this, new GetModulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoadComboBox[] GetProjects(string UsuarioID, string ModuloID) {
            object[] results = this.Invoke("GetProjects", new object[] {
                        UsuarioID,
                        ModuloID});
            return ((LoadComboBox[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectsAsync(string UsuarioID, string ModuloID) {
            this.GetProjectsAsync(UsuarioID, ModuloID, null);
        }
        
        /// <remarks/>
        public void GetProjectsAsync(string UsuarioID, string ModuloID, object userState) {
            if ((this.GetProjectsOperationCompleted == null)) {
                this.GetProjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectsOperationCompleted);
            }
            this.InvokeAsync("GetProjects", new object[] {
                        UsuarioID,
                        ModuloID}, this.GetProjectsOperationCompleted, userState);
        }
        
        private void OnGetProjectsOperationCompleted(object arg) {
            if ((this.GetProjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectsCompleted(this, new GetProjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadProject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpperGanttNode LoadProject(string PrgId) {
            object[] results = this.Invoke("LoadProject", new object[] {
                        PrgId});
            return ((UpperGanttNode)(results[0]));
        }
        
        /// <remarks/>
        public void LoadProjectAsync(string PrgId) {
            this.LoadProjectAsync(PrgId, null);
        }
        
        /// <remarks/>
        public void LoadProjectAsync(string PrgId, object userState) {
            if ((this.LoadProjectOperationCompleted == null)) {
                this.LoadProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadProjectOperationCompleted);
            }
            this.InvokeAsync("LoadProject", new object[] {
                        PrgId}, this.LoadProjectOperationCompleted, userState);
        }
        
        private void OnLoadProjectOperationCompleted(object arg) {
            if ((this.LoadProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadProjectCompleted(this, new LoadProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveConfigs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SaveConfigs(string operacion, string PrgId, string PrgDescripcion, string PrgModulo, string PrgObservarciones, int EstadoEstado, string PrgUnidadesTrabajo, string PrgUnidadesDuracion, string PrgHorasDia, string PrgHorasSemana, string PrgInicioProgramado, string PrgFinProgramado, int PrgDuracionProgramada, string PrgUsuario, string PrgWeekStart) {
            object[] results = this.Invoke("SaveConfigs", new object[] {
                        operacion,
                        PrgId,
                        PrgDescripcion,
                        PrgModulo,
                        PrgObservarciones,
                        EstadoEstado,
                        PrgUnidadesTrabajo,
                        PrgUnidadesDuracion,
                        PrgHorasDia,
                        PrgHorasSemana,
                        PrgInicioProgramado,
                        PrgFinProgramado,
                        PrgDuracionProgramada,
                        PrgUsuario,
                        PrgWeekStart});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveConfigsAsync(string operacion, string PrgId, string PrgDescripcion, string PrgModulo, string PrgObservarciones, int EstadoEstado, string PrgUnidadesTrabajo, string PrgUnidadesDuracion, string PrgHorasDia, string PrgHorasSemana, string PrgInicioProgramado, string PrgFinProgramado, int PrgDuracionProgramada, string PrgUsuario, string PrgWeekStart) {
            this.SaveConfigsAsync(operacion, PrgId, PrgDescripcion, PrgModulo, PrgObservarciones, EstadoEstado, PrgUnidadesTrabajo, PrgUnidadesDuracion, PrgHorasDia, PrgHorasSemana, PrgInicioProgramado, PrgFinProgramado, PrgDuracionProgramada, PrgUsuario, PrgWeekStart, null);
        }
        
        /// <remarks/>
        public void SaveConfigsAsync(
                    string operacion, 
                    string PrgId, 
                    string PrgDescripcion, 
                    string PrgModulo, 
                    string PrgObservarciones, 
                    int EstadoEstado, 
                    string PrgUnidadesTrabajo, 
                    string PrgUnidadesDuracion, 
                    string PrgHorasDia, 
                    string PrgHorasSemana, 
                    string PrgInicioProgramado, 
                    string PrgFinProgramado, 
                    int PrgDuracionProgramada, 
                    string PrgUsuario, 
                    string PrgWeekStart, 
                    object userState) {
            if ((this.SaveConfigsOperationCompleted == null)) {
                this.SaveConfigsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveConfigsOperationCompleted);
            }
            this.InvokeAsync("SaveConfigs", new object[] {
                        operacion,
                        PrgId,
                        PrgDescripcion,
                        PrgModulo,
                        PrgObservarciones,
                        EstadoEstado,
                        PrgUnidadesTrabajo,
                        PrgUnidadesDuracion,
                        PrgHorasDia,
                        PrgHorasSemana,
                        PrgInicioProgramado,
                        PrgFinProgramado,
                        PrgDuracionProgramada,
                        PrgUsuario,
                        PrgWeekStart}, this.SaveConfigsOperationCompleted, userState);
        }
        
        private void OnSaveConfigsOperationCompleted(object arg) {
            if ((this.SaveConfigsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveConfigsCompleted(this, new SaveConfigsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveWeekExceptions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SaveWeekExceptions(ConfigDays dia) {
            object[] results = this.Invoke("SaveWeekExceptions", new object[] {
                        dia});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveWeekExceptionsAsync(ConfigDays dia) {
            this.SaveWeekExceptionsAsync(dia, null);
        }
        
        /// <remarks/>
        public void SaveWeekExceptionsAsync(ConfigDays dia, object userState) {
            if ((this.SaveWeekExceptionsOperationCompleted == null)) {
                this.SaveWeekExceptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveWeekExceptionsOperationCompleted);
            }
            this.InvokeAsync("SaveWeekExceptions", new object[] {
                        dia}, this.SaveWeekExceptionsOperationCompleted, userState);
        }
        
        private void OnSaveWeekExceptionsOperationCompleted(object arg) {
            if ((this.SaveWeekExceptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveWeekExceptionsCompleted(this, new SaveWeekExceptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveProject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SaveProject(string xmlDoc) {
            object[] results = this.Invoke("SaveProject", new object[] {
                        xmlDoc});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveProjectAsync(string xmlDoc) {
            this.SaveProjectAsync(xmlDoc, null);
        }
        
        /// <remarks/>
        public void SaveProjectAsync(string xmlDoc, object userState) {
            if ((this.SaveProjectOperationCompleted == null)) {
                this.SaveProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveProjectOperationCompleted);
            }
            this.InvokeAsync("SaveProject", new object[] {
                        xmlDoc}, this.SaveProjectOperationCompleted, userState);
        }
        
        private void OnSaveProjectOperationCompleted(object arg) {
            if ((this.SaveProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveProjectCompleted(this, new SaveProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportarErrorExterno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReportarErrorExterno(ErroresAplicaciones2 error, string InformacionMaquina) {
            object[] results = this.Invoke("ReportarErrorExterno", new object[] {
                        error,
                        InformacionMaquina});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReportarErrorExternoAsync(ErroresAplicaciones2 error, string InformacionMaquina) {
            this.ReportarErrorExternoAsync(error, InformacionMaquina, null);
        }
        
        /// <remarks/>
        public void ReportarErrorExternoAsync(ErroresAplicaciones2 error, string InformacionMaquina, object userState) {
            if ((this.ReportarErrorExternoOperationCompleted == null)) {
                this.ReportarErrorExternoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportarErrorExternoOperationCompleted);
            }
            this.InvokeAsync("ReportarErrorExterno", new object[] {
                        error,
                        InformacionMaquina}, this.ReportarErrorExternoOperationCompleted, userState);
        }
        
        private void OnReportarErrorExternoOperationCompleted(object arg) {
            if ((this.ReportarErrorExternoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportarErrorExternoCompleted(this, new ReportarErrorExternoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadComboBox {
        
        private int idField;
        
        private string descripcionField;
        
        private string auxIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string AuxId {
            get {
                return this.auxIdField;
            }
            set {
                this.auxIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErroresAplicaciones2 {
        
        private string mensajeField;
        
        private string stackTraceField;
        
        private string innerExceptionField;
        
        private string fuenteField;
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        public string InnerException {
            get {
                return this.innerExceptionField;
            }
            set {
                this.innerExceptionField = value;
            }
        }
        
        /// <remarks/>
        public string Fuente {
            get {
                return this.fuenteField;
            }
            set {
                this.fuenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GanttNode {
        
        private int idField;
        
        private string itemNameField;
        
        private System.DateTime beginDateField;
        
        private System.DateTime endDateField;
        
        private string durationField;
        
        private decimal percentAdvancedField;
        
        private string parentGanttNodeField;
        
        private string precendentGanttNodeField;
        
        private int proyectoIDField;
        
        private string taskNotesField;
        
        private string asignacionesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentAdvanced {
            get {
                return this.percentAdvancedField;
            }
            set {
                this.percentAdvancedField = value;
            }
        }
        
        /// <remarks/>
        public string ParentGanttNode {
            get {
                return this.parentGanttNodeField;
            }
            set {
                this.parentGanttNodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrecendentGanttNode {
            get {
                return this.precendentGanttNodeField;
            }
            set {
                this.precendentGanttNodeField = value;
            }
        }
        
        /// <remarks/>
        public int ProyectoID {
            get {
                return this.proyectoIDField;
            }
            set {
                this.proyectoIDField = value;
            }
        }
        
        /// <remarks/>
        public string TaskNotes {
            get {
                return this.taskNotesField;
            }
            set {
                this.taskNotesField = value;
            }
        }
        
        /// <remarks/>
        public string Asignaciones {
            get {
                return this.asignacionesField;
            }
            set {
                this.asignacionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExceptionNodes {
        
        private int exceptionIdField;
        
        private int exceptionPrgIdField;
        
        private string exceptionNameField;
        
        private System.DateTime exceptionStartField;
        
        private System.DateTime exceptionFinishField;
        
        /// <remarks/>
        public int ExceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <remarks/>
        public int ExceptionPrgId {
            get {
                return this.exceptionPrgIdField;
            }
            set {
                this.exceptionPrgIdField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionName {
            get {
                return this.exceptionNameField;
            }
            set {
                this.exceptionNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExceptionStart {
            get {
                return this.exceptionStartField;
            }
            set {
                this.exceptionStartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExceptionFinish {
            get {
                return this.exceptionFinishField;
            }
            set {
                this.exceptionFinishField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfigDays {
        
        private int projectIdField;
        
        private string dayNameField;
        
        private string morningStartField;
        
        private string morningDurationField;
        
        private string afternoonStartField;
        
        private string afternoonDurationField;
        
        private string configOperationField;
        
        /// <remarks/>
        public int ProjectId {
            get {
                return this.projectIdField;
            }
            set {
                this.projectIdField = value;
            }
        }
        
        /// <remarks/>
        public string DayName {
            get {
                return this.dayNameField;
            }
            set {
                this.dayNameField = value;
            }
        }
        
        /// <remarks/>
        public string MorningStart {
            get {
                return this.morningStartField;
            }
            set {
                this.morningStartField = value;
            }
        }
        
        /// <remarks/>
        public string MorningDuration {
            get {
                return this.morningDurationField;
            }
            set {
                this.morningDurationField = value;
            }
        }
        
        /// <remarks/>
        public string AfternoonStart {
            get {
                return this.afternoonStartField;
            }
            set {
                this.afternoonStartField = value;
            }
        }
        
        /// <remarks/>
        public string AfternoonDuration {
            get {
                return this.afternoonDurationField;
            }
            set {
                this.afternoonDurationField = value;
            }
        }
        
        /// <remarks/>
        public string ConfigOperation {
            get {
                return this.configOperationField;
            }
            set {
                this.configOperationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpperGanttNode {
        
        private int idProjectField;
        
        private string descProjectField;
        
        private string durationUnitsField;
        
        private string workUnitsField;
        
        private string weekStartField;
        
        private int hoursPerDayField;
        
        private int hoursPerWeekField;
        
        private string scheduledStartField;
        
        private string scheduledFinishField;
        
        private int scheduledDurationField;
        
        private ConfigDays[] weekExceptionsField;
        
        private ExceptionNodes[] exceptionsField;
        
        private GanttNode[] lowerGanttNodesField;
        
        /// <remarks/>
        public int IdProject {
            get {
                return this.idProjectField;
            }
            set {
                this.idProjectField = value;
            }
        }
        
        /// <remarks/>
        public string DescProject {
            get {
                return this.descProjectField;
            }
            set {
                this.descProjectField = value;
            }
        }
        
        /// <remarks/>
        public string DurationUnits {
            get {
                return this.durationUnitsField;
            }
            set {
                this.durationUnitsField = value;
            }
        }
        
        /// <remarks/>
        public string WorkUnits {
            get {
                return this.workUnitsField;
            }
            set {
                this.workUnitsField = value;
            }
        }
        
        /// <remarks/>
        public string WeekStart {
            get {
                return this.weekStartField;
            }
            set {
                this.weekStartField = value;
            }
        }
        
        /// <remarks/>
        public int HoursPerDay {
            get {
                return this.hoursPerDayField;
            }
            set {
                this.hoursPerDayField = value;
            }
        }
        
        /// <remarks/>
        public int HoursPerWeek {
            get {
                return this.hoursPerWeekField;
            }
            set {
                this.hoursPerWeekField = value;
            }
        }
        
        /// <remarks/>
        public string ScheduledStart {
            get {
                return this.scheduledStartField;
            }
            set {
                this.scheduledStartField = value;
            }
        }
        
        /// <remarks/>
        public string ScheduledFinish {
            get {
                return this.scheduledFinishField;
            }
            set {
                this.scheduledFinishField = value;
            }
        }
        
        /// <remarks/>
        public int ScheduledDuration {
            get {
                return this.scheduledDurationField;
            }
            set {
                this.scheduledDurationField = value;
            }
        }
        
        /// <remarks/>
        public ConfigDays[] WeekExceptions {
            get {
                return this.weekExceptionsField;
            }
            set {
                this.weekExceptionsField = value;
            }
        }
        
        /// <remarks/>
        public ExceptionNodes[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
        
        /// <remarks/>
        public GanttNode[] LowerGanttNodes {
            get {
                return this.lowerGanttNodesField;
            }
            set {
                this.lowerGanttNodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetModulesCompletedEventHandler(object sender, GetModulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoadComboBox[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoadComboBox[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProjectsCompletedEventHandler(object sender, GetProjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoadComboBox[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoadComboBox[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoadProjectCompletedEventHandler(object sender, LoadProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpperGanttNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpperGanttNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveConfigsCompletedEventHandler(object sender, SaveConfigsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveConfigsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveConfigsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveWeekExceptionsCompletedEventHandler(object sender, SaveWeekExceptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveWeekExceptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveWeekExceptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveProjectCompletedEventHandler(object sender, SaveProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReportarErrorExternoCompletedEventHandler(object sender, ReportarErrorExternoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportarErrorExternoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportarErrorExternoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591