//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SincoExcel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cambios Guardados correctamente.")]
        public string MsGuardarCambiosCompleto {
            get {
                return ((string)(this["MsGuardarCambiosCompleto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se cargó correctamente el archivo de licencia.")]
        public string MsErrorCargarArchivoLicencia {
            get {
                return ((string)(this["MsErrorCargarArchivoLicencia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se actualizó el valor del nuevo color.")]
        public string MsErrorCambiarColorConfiguracion {
            get {
                return ((string)(this["MsErrorCambiarColorConfiguracion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se cargaron correctamente los datos de su licencia, consulte al administrador " +
            "del sistema.")]
        public string MsErrorIniciarArchivoLicencia {
            get {
                return ((string)(this["MsErrorIniciarArchivoLicencia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Datos incorrectos, Verifique la contraseña o consulte con el administrador del si" +
            "stema.")]
        public string MsErrorDatosLoginUsuario {
            get {
                return ((string)(this["MsErrorDatosLoginUsuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Por favor complete todos los campos.")]
        public string MsCompletarDatosRequeridosLogin {
            get {
                return ((string)(this["MsCompletarDatosRequeridosLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se cargó la lista de sucursales del usuario, verifique que su archivo de licen" +
            "cia sea válido y que tenga conexión con SINCO ERP.")]
        public string MsErrorCargarListaSucursalesLogin {
            get {
                return ((string)(this["MsErrorCargarListaSucursalesLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se creó el control, verifique que esté ubicado en una celda Válida.")]
        public string MsErrorCreacionControl {
            get {
                return ((string)(this["MsErrorCreacionControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea agregar la nueva Fuente externa?")]
        public string MsPreguntaAgregarFuenteExterna {
            get {
                return ((string)(this["MsPreguntaAgregarFuenteExterna"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El valor de la celda para la fuente externa no fué modificado.")]
        public string MsErrorModificarCeldaFuenteExterna {
            get {
                return ((string)(this["MsErrorModificarCeldaFuenteExterna"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Esta seguro que desea eliminar la fuente externa?")]
        public string MsPreguntaEliminarFueneExterna {
            get {
                return ((string)(this["MsPreguntaEliminarFueneExterna"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se Eliminó la Fuente Externa, verifique que no este asociado previamente a un " +
            "descriptor.")]
        public string MsErrorEliminarFuenteExterna {
            get {
                return ((string)(this["MsErrorEliminarFuenteExterna"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Seleccione una fuente externa por favor.")]
        public string MsSeleccionarFuenteExterna {
            get {
                return ((string)(this["MsSeleccionarFuenteExterna"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El descriptor ya está registrado, desea actualizarlo?")]
        public string MsPreguntaConfirmarActualizarDescriptor {
            get {
                return ((string)(this["MsPreguntaConfirmarActualizarDescriptor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se agregó el descriptor. Verifique que tenga seleccionada una categoria válida" +
            "")]
        public string MsErrorAgregarDescriptor {
            get {
                return ((string)(this["MsErrorAgregarDescriptor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Por favor complete todos los campos.")]
        public string MsCompletarDatosRequeridosDescriptor {
            get {
                return ((string)(this["MsCompletarDatosRequeridosDescriptor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se puede eliminar la fila seleccionada por que tiene descriptores asociados.")]
        public string MsErrorEliminarFilaExcel {
            get {
                return ((string)(this["MsErrorEliminarFilaExcel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se puede eliminar la Columna seleccionada por que tiene descriptores asociados" +
            ".")]
        public string MsErrorEliminarColumnaExcel {
            get {
                return ((string)(this["MsErrorEliminarColumnaExcel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se completó la operación.")]
        public string MsErrorOpcionesDiseñoExcel {
            get {
                return ((string)(this["MsErrorOpcionesDiseñoExcel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea eliminar el descriptor de la tabla?")]
        public string MsPreguntaEliminarDescriptorTabla {
            get {
                return ((string)(this["MsPreguntaEliminarDescriptorTabla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ya existe una tabla llamada: {0}   .  No puede crear dos tablas con el mismo nomb" +
            "re, por favor cambie el nombre de la tabla.")]
        public string MSCambiarNombreTablaDuplicado {
            get {
                return ((string)(this["MSCambiarNombreTablaDuplicado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("La hoja actual no esta asociada a una plantilla, por favor abra una plantilla vál" +
            "ida.")]
        public string MsErrorPlantillaNoValida {
            get {
                return ((string)(this["MsErrorPlantillaNoValida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Los campos: Nombre de Tabla y número de Filas son Obligatorios.  Verifique que ha" +
            "ya añadido columnas a la tabla.")]
        public string MsCompletarInformacionRequeridaCreacionTabla {
            get {
                return ((string)(this["MsCompletarInformacionRequeridaCreacionTabla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ya existe un descriptor principal en el formato.  Recuerde que solo debe crear un" +
            " descriptor principal por formato.")]
        public string MsInformacionDescriptorPrincipalRegistrado {
            get {
                return ((string)(this["MsInformacionDescriptorPrincipalRegistrado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea eliminar el control?")]
        public string MsEliminarControl {
            get {
                return ((string)(this["MsEliminarControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El control pertenece a una tabla de datos, desea eliminar la tabla?")]
        public string MsEliminarControlTabla {
            get {
                return ((string)(this["MsEliminarControlTabla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El elemento: {0}  no se eliminó.")]
        public string MsErrorEliminarControl {
            get {
                return ((string)(this["MsErrorEliminarControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Los elementos de la tabla fueron eliminados correctamente.")]
        public string MsControlesTablaEliminadosCorrectamente {
            get {
                return ((string)(this["MsControlesTablaEliminadosCorrectamente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Algunos elementos de la tabla no se eliminaron.")]
        public string MsErrorEliminarControlesTabla {
            get {
                return ((string)(this["MsErrorEliminarControlesTabla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea eliminar el elemento:  {0} ?")]
        public string MsConfirmarEliminarDescriptor {
            get {
                return ((string)(this["MsConfirmarEliminarDescriptor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se eliminó el elemento, verifique que sea un descriptor válido.")]
        public string MsErrorEliminarDescriptor {
            get {
                return ((string)(this["MsErrorEliminarDescriptor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Los campos categoria y descriptor son obligatorios.")]
        public string MsRequeridoAgregarDescriptor {
            get {
                return ((string)(this["MsRequeridoAgregarDescriptor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se actualizó la información del arbol de categorias.")]
        public string MsErrorActualizarArbolCategorias {
            get {
                return ((string)(this["MsErrorActualizarArbolCategorias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No puede editar la fila seleccionada.")]
        public string MsErrorEditarRegistroFuenteExterna {
            get {
                return ((string)(this["MsErrorEditarRegistroFuenteExterna"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El formato tiene asociado un archivo, desea cargarlo?")]
        public string MsPreguntaCargarFormatoExistente {
            get {
                return ((string)(this["MsPreguntaCargarFormatoExistente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ocurrió un error al cargar el archivo. Verifique que el archivo esté correctament" +
            "e creado. ")]
        public string MsErrorCargarArchivo {
            get {
                return ((string)(this["MsErrorCargarArchivo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verifique la tabla de configuración de SGC.")]
        public string MsErrorVerificarConfiguracionISO {
            get {
                return ((string)(this["MsErrorVerificarConfiguracionISO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Algunos elementos no se crearon correctamente.")]
        public string MsErrorCargarControlesTipologia {
            get {
                return ((string)(this["MsErrorCargarControlesTipologia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plantilla de Formato Creada Correctamente.")]
        public string MsPlantillaCreadaCorrectamente {
            get {
                return ((string)(this["MsPlantillaCreadaCorrectamente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se cargó correctamente la plantila.")]
        public string MsErrorCargarPlantilla {
            get {
                return ((string)(this["MsErrorCargarPlantilla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Existe un formato abierto, por favor cierre el formato. ")]
        public string MsCerrarFormatoAbierto {
            get {
                return ((string)(this["MsCerrarFormatoAbierto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Por favor seleccione un formato.")]
        public string MsSeleccionarFormato {
            get {
                return ((string)(this["MsSeleccionarFormato"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Las validaciones son correctas.")]
        public string MsResultadoValidacionesOK {
            get {
                return ((string)(this["MsResultadoValidacionesOK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Por favor, configure una carpeta temporal para el complemento Sinco ERP.")]
        public string MsConfigurarRutaTemporal {
            get {
                return ((string)(this["MsConfigurarRutaTemporal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Su sesión ha expirado.  Desea iniciar nuevamente una sesión?")]
        public string MsSesionCerrada {
            get {
                return ((string)(this["MsSesionCerrada"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea guardar la plantilla actual?")]
        public string MsGuardarPlantilla {
            get {
                return ((string)(this["MsGuardarPlantilla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El formato no se registró correctamente.")]
        public string MsErrorGuardarFormato {
            get {
                return ((string)(this["MsErrorGuardarFormato"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error al intentar cargar los controles creados, por favor vuelva a abrir el forma" +
            "to.")]
        public string MsErrorCargarControl {
            get {
                return ((string)(this["MsErrorCargarControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea guardar el formato diligenciado actual?")]
        public string MsPreguntaGuardarFormatoDiligenciado {
            get {
                return ((string)(this["MsPreguntaGuardarFormatoDiligenciado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea volver a cargar el formato?")]
        public string MsVolvarCargarFormato {
            get {
                return ((string)(this["MsVolvarCargarFormato"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desea cerrar el Formato actual?")]
        public string MsCerrarFormato {
            get {
                return ((string)(this["MsCerrarFormato"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El texto ingresado no es correcto.  Tipo de Dato:  {0}")]
        public string MsErrorFormatoTextoIngresado {
            get {
                return ((string)(this["MsErrorFormatoTextoIngresado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Faltan los siguientes descriptores obligatorios o su contenido no es correcto: ")]
        public string MsErrorDescriptoresFaltantes {
            get {
                return ((string)(this["MsErrorDescriptoresFaltantes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El Formato se guardó correctamente.")]
        public string MsGuardarFormatoCorrecto {
            get {
                return ((string)(this["MsGuardarFormatoCorrecto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se actualizó la información.")]
        public string MsErrorCargarInformacionInicial {
            get {
                return ((string)(this["MsErrorCargarInformacionInicial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No se creó el control Tabla de Datos.")]
        public string MsErrorCrearTabla {
            get {
                return ((string)(this["MsErrorCrearTabla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No fue posible eliminar el descriptor, es posible que se encuentre en uso en la a" +
            "plicación.")]
        public string MsErrorEliminarDescriptorSGD {
            get {
                return ((string)(this["MsErrorEliminarDescriptorSGD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("El descriptor seleccionado ya se encuentra registrado en la tabla.")]
        public string MsErrorAgregarDescriptorTabla {
            get {
                return ((string)(this["MsErrorAgregarDescriptorTabla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tiene un formato asociado al sistema de Gestión de Calidad abierto, recuerde que " +
            "si desea guardarlo debe utilizar la opción Guardar del Menu de Sinco ERP.")]
        public string MsGuardarFormatoOpcionGuardar {
            get {
                return ((string)(this["MsGuardarFormatoOpcionGuardar"]));
            }
        }
    }
}
