//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.235.
// 
#pragma warning disable 1591

namespace SincoOfficeLibrerias.wsSGCdocumentos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSGCdocumentosSoap", Namespace="http://tempuri.org/")]
    public partial class wsSGCdocumentos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CRUDformatosSGCOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerArchivosFormatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarArchivoFormatoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsSGCdocumentos() {
            this.Url = global::SincoOfficeLibrerias.Properties.Settings.Default.SincoOfficeLibrerias_wsSGCdocumentos_wsSGCdocumentos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CRUDformatosSGCCompletedEventHandler CRUDformatosSGCCompleted;
        
        /// <remarks/>
        public event LeerArchivosFormatosCompletedEventHandler LeerArchivosFormatosCompleted;
        
        /// <remarks/>
        public event GuardarArchivoFormatoCompletedEventHandler GuardarArchivoFormatoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CRUDformatosSGC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode CRUDformatosSGC([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionID, string Operacion) {
            object[] results = this.Invoke("CRUDformatosSGC", new object[] {
                        SessionID,
                        Operacion});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void CRUDformatosSGCAsync(byte[] SessionID, string Operacion) {
            this.CRUDformatosSGCAsync(SessionID, Operacion, null);
        }
        
        /// <remarks/>
        public void CRUDformatosSGCAsync(byte[] SessionID, string Operacion, object userState) {
            if ((this.CRUDformatosSGCOperationCompleted == null)) {
                this.CRUDformatosSGCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCRUDformatosSGCOperationCompleted);
            }
            this.InvokeAsync("CRUDformatosSGC", new object[] {
                        SessionID,
                        Operacion}, this.CRUDformatosSGCOperationCompleted, userState);
        }
        
        private void OnCRUDformatosSGCOperationCompleted(object arg) {
            if ((this.CRUDformatosSGCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CRUDformatosSGCCompleted(this, new CRUDformatosSGCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeerArchivosFormatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] LeerArchivosFormatos([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionID, string RutaArchivo) {
            object[] results = this.Invoke("LeerArchivosFormatos", new object[] {
                        SessionID,
                        RutaArchivo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void LeerArchivosFormatosAsync(byte[] SessionID, string RutaArchivo) {
            this.LeerArchivosFormatosAsync(SessionID, RutaArchivo, null);
        }
        
        /// <remarks/>
        public void LeerArchivosFormatosAsync(byte[] SessionID, string RutaArchivo, object userState) {
            if ((this.LeerArchivosFormatosOperationCompleted == null)) {
                this.LeerArchivosFormatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerArchivosFormatosOperationCompleted);
            }
            this.InvokeAsync("LeerArchivosFormatos", new object[] {
                        SessionID,
                        RutaArchivo}, this.LeerArchivosFormatosOperationCompleted, userState);
        }
        
        private void OnLeerArchivosFormatosOperationCompleted(object arg) {
            if ((this.LeerArchivosFormatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerArchivosFormatosCompleted(this, new LeerArchivosFormatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarArchivoFormato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardarArchivoFormato([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionID, string RutaArchivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Archivo) {
            object[] results = this.Invoke("GuardarArchivoFormato", new object[] {
                        SessionID,
                        RutaArchivo,
                        Archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarArchivoFormatoAsync(byte[] SessionID, string RutaArchivo, byte[] Archivo) {
            this.GuardarArchivoFormatoAsync(SessionID, RutaArchivo, Archivo, null);
        }
        
        /// <remarks/>
        public void GuardarArchivoFormatoAsync(byte[] SessionID, string RutaArchivo, byte[] Archivo, object userState) {
            if ((this.GuardarArchivoFormatoOperationCompleted == null)) {
                this.GuardarArchivoFormatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarArchivoFormatoOperationCompleted);
            }
            this.InvokeAsync("GuardarArchivoFormato", new object[] {
                        SessionID,
                        RutaArchivo,
                        Archivo}, this.GuardarArchivoFormatoOperationCompleted, userState);
        }
        
        private void OnGuardarArchivoFormatoOperationCompleted(object arg) {
            if ((this.GuardarArchivoFormatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarArchivoFormatoCompleted(this, new GuardarArchivoFormatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CRUDformatosSGCCompletedEventHandler(object sender, CRUDformatosSGCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CRUDformatosSGCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CRUDformatosSGCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LeerArchivosFormatosCompletedEventHandler(object sender, LeerArchivosFormatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerArchivosFormatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerArchivosFormatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GuardarArchivoFormatoCompletedEventHandler(object sender, GuardarArchivoFormatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarArchivoFormatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarArchivoFormatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591