//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace SincoOfficeLibrerias.wsOfficeSGD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsOfficeSGDSoap", Namespace="http://tempuri.org/")]
    public partial class wsOfficeSGD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaDescriptoresCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FuenteDatosDescriptoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPrecedenciasDescriptorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CRUDFuenteExternaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarFormatoPlantillaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarFormatoPlantillaDiligenciadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeerArchivosFormatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarArchivoFormatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarDescriptorPorCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaInformacionInicialOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroErroresComplementosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarAccesoUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDescriptoresDocumentosExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarDescriptorCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PasosResponsablesConsultaTSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsOfficeSGD() {
            this.Url = global::SincoOfficeLibrerias.Properties.Settings.Default.SincoOfficeLibrerias_wsOfficeSGD_wsOfficeSGD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaDescriptoresCategoriaCompletedEventHandler ConsultaDescriptoresCategoriaCompleted;
        
        /// <remarks/>
        public event FuenteDatosDescriptoresCompletedEventHandler FuenteDatosDescriptoresCompleted;
        
        /// <remarks/>
        public event ConsultarPrecedenciasDescriptorCompletedEventHandler ConsultarPrecedenciasDescriptorCompleted;
        
        /// <remarks/>
        public event CRUDFuenteExternaCompletedEventHandler CRUDFuenteExternaCompleted;
        
        /// <remarks/>
        public event GuardarFormatoPlantillaCompletedEventHandler GuardarFormatoPlantillaCompleted;
        
        /// <remarks/>
        public event GuardarFormatoPlantillaDiligenciadosCompletedEventHandler GuardarFormatoPlantillaDiligenciadosCompleted;
        
        /// <remarks/>
        public event LeerArchivosFormatosCompletedEventHandler LeerArchivosFormatosCompleted;
        
        /// <remarks/>
        public event GuardarArchivoFormatoCompletedEventHandler GuardarArchivoFormatoCompleted;
        
        /// <remarks/>
        public event AgregarDescriptorPorCategoriaCompletedEventHandler AgregarDescriptorPorCategoriaCompleted;
        
        /// <remarks/>
        public event ConsultaInformacionInicialCompletedEventHandler ConsultaInformacionInicialCompleted;
        
        /// <remarks/>
        public event RegistroErroresComplementosCompletedEventHandler RegistroErroresComplementosCompleted;
        
        /// <remarks/>
        public event ValidarAccesoUsuariosCompletedEventHandler ValidarAccesoUsuariosCompleted;
        
        /// <remarks/>
        public event ActualizarDescriptoresDocumentosExcelCompletedEventHandler ActualizarDescriptoresDocumentosExcelCompleted;
        
        /// <remarks/>
        public event GuardarDescriptorCategoriaCompletedEventHandler GuardarDescriptorCategoriaCompleted;
        
        /// <remarks/>
        public event PasosResponsablesConsultaTSCompletedEventHandler PasosResponsablesConsultaTSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaDescriptoresCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultaDescriptoresCategoria([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string Categoria) {
            object[] results = this.Invoke("ConsultaDescriptoresCategoria", new object[] {
                        SessionId,
                        operacion,
                        Categoria});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDescriptoresCategoriaAsync(byte[] SessionId, string operacion, string Categoria) {
            this.ConsultaDescriptoresCategoriaAsync(SessionId, operacion, Categoria, null);
        }
        
        /// <remarks/>
        public void ConsultaDescriptoresCategoriaAsync(byte[] SessionId, string operacion, string Categoria, object userState) {
            if ((this.ConsultaDescriptoresCategoriaOperationCompleted == null)) {
                this.ConsultaDescriptoresCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDescriptoresCategoriaOperationCompleted);
            }
            this.InvokeAsync("ConsultaDescriptoresCategoria", new object[] {
                        SessionId,
                        operacion,
                        Categoria}, this.ConsultaDescriptoresCategoriaOperationCompleted, userState);
        }
        
        private void OnConsultaDescriptoresCategoriaOperationCompleted(object arg) {
            if ((this.ConsultaDescriptoresCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDescriptoresCategoriaCompleted(this, new ConsultaDescriptoresCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FuenteDatosDescriptores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode FuenteDatosDescriptores([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string Descriptor, string Variables, string Busqueda) {
            object[] results = this.Invoke("FuenteDatosDescriptores", new object[] {
                        SessionId,
                        Descriptor,
                        Variables,
                        Busqueda});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void FuenteDatosDescriptoresAsync(byte[] SessionId, string Descriptor, string Variables, string Busqueda) {
            this.FuenteDatosDescriptoresAsync(SessionId, Descriptor, Variables, Busqueda, null);
        }
        
        /// <remarks/>
        public void FuenteDatosDescriptoresAsync(byte[] SessionId, string Descriptor, string Variables, string Busqueda, object userState) {
            if ((this.FuenteDatosDescriptoresOperationCompleted == null)) {
                this.FuenteDatosDescriptoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFuenteDatosDescriptoresOperationCompleted);
            }
            this.InvokeAsync("FuenteDatosDescriptores", new object[] {
                        SessionId,
                        Descriptor,
                        Variables,
                        Busqueda}, this.FuenteDatosDescriptoresOperationCompleted, userState);
        }
        
        private void OnFuenteDatosDescriptoresOperationCompleted(object arg) {
            if ((this.FuenteDatosDescriptoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FuenteDatosDescriptoresCompleted(this, new FuenteDatosDescriptoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarPrecedenciasDescriptor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ConsultarPrecedenciasDescriptor([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string IdDescriptor) {
            object[] results = this.Invoke("ConsultarPrecedenciasDescriptor", new object[] {
                        SessionId,
                        IdDescriptor});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPrecedenciasDescriptorAsync(byte[] SessionId, string IdDescriptor) {
            this.ConsultarPrecedenciasDescriptorAsync(SessionId, IdDescriptor, null);
        }
        
        /// <remarks/>
        public void ConsultarPrecedenciasDescriptorAsync(byte[] SessionId, string IdDescriptor, object userState) {
            if ((this.ConsultarPrecedenciasDescriptorOperationCompleted == null)) {
                this.ConsultarPrecedenciasDescriptorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPrecedenciasDescriptorOperationCompleted);
            }
            this.InvokeAsync("ConsultarPrecedenciasDescriptor", new object[] {
                        SessionId,
                        IdDescriptor}, this.ConsultarPrecedenciasDescriptorOperationCompleted, userState);
        }
        
        private void OnConsultarPrecedenciasDescriptorOperationCompleted(object arg) {
            if ((this.ConsultarPrecedenciasDescriptorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPrecedenciasDescriptorCompleted(this, new ConsultarPrecedenciasDescriptorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CRUDFuenteExterna", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode CRUDFuenteExterna([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, int idFuente, string descripcion, int usuario, string texto, bool activo) {
            object[] results = this.Invoke("CRUDFuenteExterna", new object[] {
                        SessionId,
                        operacion,
                        idFuente,
                        descripcion,
                        usuario,
                        texto,
                        activo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void CRUDFuenteExternaAsync(byte[] SessionId, string operacion, int idFuente, string descripcion, int usuario, string texto, bool activo) {
            this.CRUDFuenteExternaAsync(SessionId, operacion, idFuente, descripcion, usuario, texto, activo, null);
        }
        
        /// <remarks/>
        public void CRUDFuenteExternaAsync(byte[] SessionId, string operacion, int idFuente, string descripcion, int usuario, string texto, bool activo, object userState) {
            if ((this.CRUDFuenteExternaOperationCompleted == null)) {
                this.CRUDFuenteExternaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCRUDFuenteExternaOperationCompleted);
            }
            this.InvokeAsync("CRUDFuenteExterna", new object[] {
                        SessionId,
                        operacion,
                        idFuente,
                        descripcion,
                        usuario,
                        texto,
                        activo}, this.CRUDFuenteExternaOperationCompleted, userState);
        }
        
        private void OnCRUDFuenteExternaOperationCompleted(object arg) {
            if ((this.CRUDFuenteExternaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CRUDFuenteExternaCompleted(this, new CRUDFuenteExternaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guardar Formatos", RequestElementName="Guardar Formatos", RequestNamespace="http://tempuri.org/", ResponseElementName="Guardar FormatosResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Guardar FormatosResult")]
        public System.Xml.XmlNode GuardarFormatoPlantilla([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string nombreArchivo, int usuarioRegistro, string NombreTipologia, int IdEmpresa, string RutaArchivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ArchivoBinario, int SFVid, int SubserieFormato, string XMLelementos) {
            object[] results = this.Invoke("GuardarFormatoPlantilla", new object[] {
                        SessionId,
                        operacion,
                        nombreArchivo,
                        usuarioRegistro,
                        NombreTipologia,
                        IdEmpresa,
                        RutaArchivo,
                        ArchivoBinario,
                        SFVid,
                        SubserieFormato,
                        XMLelementos});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarFormatoPlantillaAsync(byte[] SessionId, string operacion, string nombreArchivo, int usuarioRegistro, string NombreTipologia, int IdEmpresa, string RutaArchivo, byte[] ArchivoBinario, int SFVid, int SubserieFormato, string XMLelementos) {
            this.GuardarFormatoPlantillaAsync(SessionId, operacion, nombreArchivo, usuarioRegistro, NombreTipologia, IdEmpresa, RutaArchivo, ArchivoBinario, SFVid, SubserieFormato, XMLelementos, null);
        }
        
        /// <remarks/>
        public void GuardarFormatoPlantillaAsync(byte[] SessionId, string operacion, string nombreArchivo, int usuarioRegistro, string NombreTipologia, int IdEmpresa, string RutaArchivo, byte[] ArchivoBinario, int SFVid, int SubserieFormato, string XMLelementos, object userState) {
            if ((this.GuardarFormatoPlantillaOperationCompleted == null)) {
                this.GuardarFormatoPlantillaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarFormatoPlantillaOperationCompleted);
            }
            this.InvokeAsync("GuardarFormatoPlantilla", new object[] {
                        SessionId,
                        operacion,
                        nombreArchivo,
                        usuarioRegistro,
                        NombreTipologia,
                        IdEmpresa,
                        RutaArchivo,
                        ArchivoBinario,
                        SFVid,
                        SubserieFormato,
                        XMLelementos}, this.GuardarFormatoPlantillaOperationCompleted, userState);
        }
        
        private void OnGuardarFormatoPlantillaOperationCompleted(object arg) {
            if ((this.GuardarFormatoPlantillaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarFormatoPlantillaCompleted(this, new GuardarFormatoPlantillaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guardar Formatos Diligenciados", RequestElementName="Guardar Formatos Diligenciados", RequestNamespace="http://tempuri.org/", ResponseElementName="Guardar Formatos DiligenciadosResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Guardar Formatos DiligenciadosResult")]
        public System.Xml.XmlNode GuardarFormatoPlantillaDiligenciados([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string nombreArchivo, int usuarioRegistro, string NombreTipologia, int IdEmpresa, string RutaArchivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] ArchivoBinario, int SFVid, int SubserieFormato, string XMLelementos, string IdSucursal, string XmlPasosUsuario) {
            object[] results = this.Invoke("GuardarFormatoPlantillaDiligenciados", new object[] {
                        SessionId,
                        operacion,
                        nombreArchivo,
                        usuarioRegistro,
                        NombreTipologia,
                        IdEmpresa,
                        RutaArchivo,
                        ArchivoBinario,
                        SFVid,
                        SubserieFormato,
                        XMLelementos,
                        IdSucursal,
                        XmlPasosUsuario});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarFormatoPlantillaDiligenciadosAsync(byte[] SessionId, string operacion, string nombreArchivo, int usuarioRegistro, string NombreTipologia, int IdEmpresa, string RutaArchivo, byte[] ArchivoBinario, int SFVid, int SubserieFormato, string XMLelementos, string IdSucursal, string XmlPasosUsuario) {
            this.GuardarFormatoPlantillaDiligenciadosAsync(SessionId, operacion, nombreArchivo, usuarioRegistro, NombreTipologia, IdEmpresa, RutaArchivo, ArchivoBinario, SFVid, SubserieFormato, XMLelementos, IdSucursal, XmlPasosUsuario, null);
        }
        
        /// <remarks/>
        public void GuardarFormatoPlantillaDiligenciadosAsync(byte[] SessionId, string operacion, string nombreArchivo, int usuarioRegistro, string NombreTipologia, int IdEmpresa, string RutaArchivo, byte[] ArchivoBinario, int SFVid, int SubserieFormato, string XMLelementos, string IdSucursal, string XmlPasosUsuario, object userState) {
            if ((this.GuardarFormatoPlantillaDiligenciadosOperationCompleted == null)) {
                this.GuardarFormatoPlantillaDiligenciadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarFormatoPlantillaDiligenciadosOperationCompleted);
            }
            this.InvokeAsync("GuardarFormatoPlantillaDiligenciados", new object[] {
                        SessionId,
                        operacion,
                        nombreArchivo,
                        usuarioRegistro,
                        NombreTipologia,
                        IdEmpresa,
                        RutaArchivo,
                        ArchivoBinario,
                        SFVid,
                        SubserieFormato,
                        XMLelementos,
                        IdSucursal,
                        XmlPasosUsuario}, this.GuardarFormatoPlantillaDiligenciadosOperationCompleted, userState);
        }
        
        private void OnGuardarFormatoPlantillaDiligenciadosOperationCompleted(object arg) {
            if ((this.GuardarFormatoPlantillaDiligenciadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarFormatoPlantillaDiligenciadosCompleted(this, new GuardarFormatoPlantillaDiligenciadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeerArchivosFormatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] LeerArchivosFormatos([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string RutaArchivo) {
            object[] results = this.Invoke("LeerArchivosFormatos", new object[] {
                        SessionId,
                        RutaArchivo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void LeerArchivosFormatosAsync(byte[] SessionId, string RutaArchivo) {
            this.LeerArchivosFormatosAsync(SessionId, RutaArchivo, null);
        }
        
        /// <remarks/>
        public void LeerArchivosFormatosAsync(byte[] SessionId, string RutaArchivo, object userState) {
            if ((this.LeerArchivosFormatosOperationCompleted == null)) {
                this.LeerArchivosFormatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeerArchivosFormatosOperationCompleted);
            }
            this.InvokeAsync("LeerArchivosFormatos", new object[] {
                        SessionId,
                        RutaArchivo}, this.LeerArchivosFormatosOperationCompleted, userState);
        }
        
        private void OnLeerArchivosFormatosOperationCompleted(object arg) {
            if ((this.LeerArchivosFormatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeerArchivosFormatosCompleted(this, new LeerArchivosFormatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarArchivoFormato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardarArchivoFormato([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string RutaArchivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Archivo) {
            object[] results = this.Invoke("GuardarArchivoFormato", new object[] {
                        SessionId,
                        RutaArchivo,
                        Archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarArchivoFormatoAsync(byte[] SessionId, string RutaArchivo, byte[] Archivo) {
            this.GuardarArchivoFormatoAsync(SessionId, RutaArchivo, Archivo, null);
        }
        
        /// <remarks/>
        public void GuardarArchivoFormatoAsync(byte[] SessionId, string RutaArchivo, byte[] Archivo, object userState) {
            if ((this.GuardarArchivoFormatoOperationCompleted == null)) {
                this.GuardarArchivoFormatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarArchivoFormatoOperationCompleted);
            }
            this.InvokeAsync("GuardarArchivoFormato", new object[] {
                        SessionId,
                        RutaArchivo,
                        Archivo}, this.GuardarArchivoFormatoOperationCompleted, userState);
        }
        
        private void OnGuardarArchivoFormatoOperationCompleted(object arg) {
            if ((this.GuardarArchivoFormatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarArchivoFormatoCompleted(this, new GuardarArchivoFormatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarDescriptorPorCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AgregarDescriptorPorCategoria([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string DESid, string DESdescripcion, string DESobservacion, string DEStipoDato, string DCCcategoria, string DESfuenteExterna) {
            object[] results = this.Invoke("AgregarDescriptorPorCategoria", new object[] {
                        SessionId,
                        operacion,
                        DESid,
                        DESdescripcion,
                        DESobservacion,
                        DEStipoDato,
                        DCCcategoria,
                        DESfuenteExterna});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarDescriptorPorCategoriaAsync(byte[] SessionId, string operacion, string DESid, string DESdescripcion, string DESobservacion, string DEStipoDato, string DCCcategoria, string DESfuenteExterna) {
            this.AgregarDescriptorPorCategoriaAsync(SessionId, operacion, DESid, DESdescripcion, DESobservacion, DEStipoDato, DCCcategoria, DESfuenteExterna, null);
        }
        
        /// <remarks/>
        public void AgregarDescriptorPorCategoriaAsync(byte[] SessionId, string operacion, string DESid, string DESdescripcion, string DESobservacion, string DEStipoDato, string DCCcategoria, string DESfuenteExterna, object userState) {
            if ((this.AgregarDescriptorPorCategoriaOperationCompleted == null)) {
                this.AgregarDescriptorPorCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarDescriptorPorCategoriaOperationCompleted);
            }
            this.InvokeAsync("AgregarDescriptorPorCategoria", new object[] {
                        SessionId,
                        operacion,
                        DESid,
                        DESdescripcion,
                        DESobservacion,
                        DEStipoDato,
                        DCCcategoria,
                        DESfuenteExterna}, this.AgregarDescriptorPorCategoriaOperationCompleted, userState);
        }
        
        private void OnAgregarDescriptorPorCategoriaOperationCompleted(object arg) {
            if ((this.AgregarDescriptorPorCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarDescriptorPorCategoriaCompleted(this, new AgregarDescriptorPorCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaInformacionInicial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaInformacionInicial([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string Categoria) {
            object[] results = this.Invoke("ConsultaInformacionInicial", new object[] {
                        SessionId,
                        operacion,
                        Categoria});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaInformacionInicialAsync(byte[] SessionId, string operacion, string Categoria) {
            this.ConsultaInformacionInicialAsync(SessionId, operacion, Categoria, null);
        }
        
        /// <remarks/>
        public void ConsultaInformacionInicialAsync(byte[] SessionId, string operacion, string Categoria, object userState) {
            if ((this.ConsultaInformacionInicialOperationCompleted == null)) {
                this.ConsultaInformacionInicialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaInformacionInicialOperationCompleted);
            }
            this.InvokeAsync("ConsultaInformacionInicial", new object[] {
                        SessionId,
                        operacion,
                        Categoria}, this.ConsultaInformacionInicialOperationCompleted, userState);
        }
        
        private void OnConsultaInformacionInicialOperationCompleted(object arg) {
            if ((this.ConsultaInformacionInicialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaInformacionInicialCompleted(this, new ConsultaInformacionInicialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistroErroresComplementos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode RegistroErroresComplementos([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string ECOGUIDerror, string ECOdescripcion, string ECOstackTrace, string ECOipCliente, string ECOnombreUsuario, string ECOinformacionSistema, string ECOsessionIdUsuario, string ECOsessionIdEmpresa, string ECOsessionIdSucursal, string ECOfechaError) {
            object[] results = this.Invoke("RegistroErroresComplementos", new object[] {
                        SessionId,
                        operacion,
                        ECOGUIDerror,
                        ECOdescripcion,
                        ECOstackTrace,
                        ECOipCliente,
                        ECOnombreUsuario,
                        ECOinformacionSistema,
                        ECOsessionIdUsuario,
                        ECOsessionIdEmpresa,
                        ECOsessionIdSucursal,
                        ECOfechaError});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroErroresComplementosAsync(byte[] SessionId, string operacion, string ECOGUIDerror, string ECOdescripcion, string ECOstackTrace, string ECOipCliente, string ECOnombreUsuario, string ECOinformacionSistema, string ECOsessionIdUsuario, string ECOsessionIdEmpresa, string ECOsessionIdSucursal, string ECOfechaError) {
            this.RegistroErroresComplementosAsync(SessionId, operacion, ECOGUIDerror, ECOdescripcion, ECOstackTrace, ECOipCliente, ECOnombreUsuario, ECOinformacionSistema, ECOsessionIdUsuario, ECOsessionIdEmpresa, ECOsessionIdSucursal, ECOfechaError, null);
        }
        
        /// <remarks/>
        public void RegistroErroresComplementosAsync(byte[] SessionId, string operacion, string ECOGUIDerror, string ECOdescripcion, string ECOstackTrace, string ECOipCliente, string ECOnombreUsuario, string ECOinformacionSistema, string ECOsessionIdUsuario, string ECOsessionIdEmpresa, string ECOsessionIdSucursal, string ECOfechaError, object userState) {
            if ((this.RegistroErroresComplementosOperationCompleted == null)) {
                this.RegistroErroresComplementosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroErroresComplementosOperationCompleted);
            }
            this.InvokeAsync("RegistroErroresComplementos", new object[] {
                        SessionId,
                        operacion,
                        ECOGUIDerror,
                        ECOdescripcion,
                        ECOstackTrace,
                        ECOipCliente,
                        ECOnombreUsuario,
                        ECOinformacionSistema,
                        ECOsessionIdUsuario,
                        ECOsessionIdEmpresa,
                        ECOsessionIdSucursal,
                        ECOfechaError}, this.RegistroErroresComplementosOperationCompleted, userState);
        }
        
        private void OnRegistroErroresComplementosOperationCompleted(object arg) {
            if ((this.RegistroErroresComplementosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroErroresComplementosCompleted(this, new RegistroErroresComplementosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarAccesoUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ValidarAccesoUsuarios([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string IdUsuario, string IdEmpresa, string IdSucursal) {
            object[] results = this.Invoke("ValidarAccesoUsuarios", new object[] {
                        SessionId,
                        operacion,
                        IdUsuario,
                        IdEmpresa,
                        IdSucursal});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarAccesoUsuariosAsync(byte[] SessionId, string operacion, string IdUsuario, string IdEmpresa, string IdSucursal) {
            this.ValidarAccesoUsuariosAsync(SessionId, operacion, IdUsuario, IdEmpresa, IdSucursal, null);
        }
        
        /// <remarks/>
        public void ValidarAccesoUsuariosAsync(byte[] SessionId, string operacion, string IdUsuario, string IdEmpresa, string IdSucursal, object userState) {
            if ((this.ValidarAccesoUsuariosOperationCompleted == null)) {
                this.ValidarAccesoUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarAccesoUsuariosOperationCompleted);
            }
            this.InvokeAsync("ValidarAccesoUsuarios", new object[] {
                        SessionId,
                        operacion,
                        IdUsuario,
                        IdEmpresa,
                        IdSucursal}, this.ValidarAccesoUsuariosOperationCompleted, userState);
        }
        
        private void OnValidarAccesoUsuariosOperationCompleted(object arg) {
            if ((this.ValidarAccesoUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarAccesoUsuariosCompleted(this, new ValidarAccesoUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarDescriptoresDocumentosExcel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ActualizarDescriptoresDocumentosExcel(string IdArchivo, string InfoDescriptores) {
            object[] results = this.Invoke("ActualizarDescriptoresDocumentosExcel", new object[] {
                        IdArchivo,
                        InfoDescriptores});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarDescriptoresDocumentosExcelAsync(string IdArchivo, string InfoDescriptores) {
            this.ActualizarDescriptoresDocumentosExcelAsync(IdArchivo, InfoDescriptores, null);
        }
        
        /// <remarks/>
        public void ActualizarDescriptoresDocumentosExcelAsync(string IdArchivo, string InfoDescriptores, object userState) {
            if ((this.ActualizarDescriptoresDocumentosExcelOperationCompleted == null)) {
                this.ActualizarDescriptoresDocumentosExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDescriptoresDocumentosExcelOperationCompleted);
            }
            this.InvokeAsync("ActualizarDescriptoresDocumentosExcel", new object[] {
                        IdArchivo,
                        InfoDescriptores}, this.ActualizarDescriptoresDocumentosExcelOperationCompleted, userState);
        }
        
        private void OnActualizarDescriptoresDocumentosExcelOperationCompleted(object arg) {
            if ((this.ActualizarDescriptoresDocumentosExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDescriptoresDocumentosExcelCompleted(this, new ActualizarDescriptoresDocumentosExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarDescriptorCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GuardarDescriptorCategoria([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string operacion, string DESid, string DESdescripcion, string DESobservacion, string DEStipoDato, string DCCcategoria, string DESfuenteExterna) {
            object[] results = this.Invoke("GuardarDescriptorCategoria", new object[] {
                        SessionId,
                        operacion,
                        DESid,
                        DESdescripcion,
                        DESobservacion,
                        DEStipoDato,
                        DCCcategoria,
                        DESfuenteExterna});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarDescriptorCategoriaAsync(byte[] SessionId, string operacion, string DESid, string DESdescripcion, string DESobservacion, string DEStipoDato, string DCCcategoria, string DESfuenteExterna) {
            this.GuardarDescriptorCategoriaAsync(SessionId, operacion, DESid, DESdescripcion, DESobservacion, DEStipoDato, DCCcategoria, DESfuenteExterna, null);
        }
        
        /// <remarks/>
        public void GuardarDescriptorCategoriaAsync(byte[] SessionId, string operacion, string DESid, string DESdescripcion, string DESobservacion, string DEStipoDato, string DCCcategoria, string DESfuenteExterna, object userState) {
            if ((this.GuardarDescriptorCategoriaOperationCompleted == null)) {
                this.GuardarDescriptorCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarDescriptorCategoriaOperationCompleted);
            }
            this.InvokeAsync("GuardarDescriptorCategoria", new object[] {
                        SessionId,
                        operacion,
                        DESid,
                        DESdescripcion,
                        DESobservacion,
                        DEStipoDato,
                        DCCcategoria,
                        DESfuenteExterna}, this.GuardarDescriptorCategoriaOperationCompleted, userState);
        }
        
        private void OnGuardarDescriptorCategoriaOperationCompleted(object arg) {
            if ((this.GuardarDescriptorCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarDescriptorCategoriaCompleted(this, new GuardarDescriptorCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PasosResponsablesConsultaTS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode PasosResponsablesConsultaTS([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] SessionId, string tipo, int sucursal) {
            object[] results = this.Invoke("PasosResponsablesConsultaTS", new object[] {
                        SessionId,
                        tipo,
                        sucursal});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void PasosResponsablesConsultaTSAsync(byte[] SessionId, string tipo, int sucursal) {
            this.PasosResponsablesConsultaTSAsync(SessionId, tipo, sucursal, null);
        }
        
        /// <remarks/>
        public void PasosResponsablesConsultaTSAsync(byte[] SessionId, string tipo, int sucursal, object userState) {
            if ((this.PasosResponsablesConsultaTSOperationCompleted == null)) {
                this.PasosResponsablesConsultaTSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPasosResponsablesConsultaTSOperationCompleted);
            }
            this.InvokeAsync("PasosResponsablesConsultaTS", new object[] {
                        SessionId,
                        tipo,
                        sucursal}, this.PasosResponsablesConsultaTSOperationCompleted, userState);
        }
        
        private void OnPasosResponsablesConsultaTSOperationCompleted(object arg) {
            if ((this.PasosResponsablesConsultaTSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PasosResponsablesConsultaTSCompleted(this, new PasosResponsablesConsultaTSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaDescriptoresCategoriaCompletedEventHandler(object sender, ConsultaDescriptoresCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDescriptoresCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDescriptoresCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FuenteDatosDescriptoresCompletedEventHandler(object sender, FuenteDatosDescriptoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FuenteDatosDescriptoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FuenteDatosDescriptoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultarPrecedenciasDescriptorCompletedEventHandler(object sender, ConsultarPrecedenciasDescriptorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPrecedenciasDescriptorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPrecedenciasDescriptorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CRUDFuenteExternaCompletedEventHandler(object sender, CRUDFuenteExternaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CRUDFuenteExternaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CRUDFuenteExternaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GuardarFormatoPlantillaCompletedEventHandler(object sender, GuardarFormatoPlantillaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarFormatoPlantillaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarFormatoPlantillaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GuardarFormatoPlantillaDiligenciadosCompletedEventHandler(object sender, GuardarFormatoPlantillaDiligenciadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarFormatoPlantillaDiligenciadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarFormatoPlantillaDiligenciadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LeerArchivosFormatosCompletedEventHandler(object sender, LeerArchivosFormatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeerArchivosFormatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeerArchivosFormatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GuardarArchivoFormatoCompletedEventHandler(object sender, GuardarArchivoFormatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarArchivoFormatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarArchivoFormatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AgregarDescriptorPorCategoriaCompletedEventHandler(object sender, AgregarDescriptorPorCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarDescriptorPorCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarDescriptorPorCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultaInformacionInicialCompletedEventHandler(object sender, ConsultaInformacionInicialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaInformacionInicialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaInformacionInicialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegistroErroresComplementosCompletedEventHandler(object sender, RegistroErroresComplementosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroErroresComplementosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroErroresComplementosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidarAccesoUsuariosCompletedEventHandler(object sender, ValidarAccesoUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarAccesoUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarAccesoUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActualizarDescriptoresDocumentosExcelCompletedEventHandler(object sender, ActualizarDescriptoresDocumentosExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarDescriptoresDocumentosExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarDescriptoresDocumentosExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GuardarDescriptorCategoriaCompletedEventHandler(object sender, GuardarDescriptorCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarDescriptorCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarDescriptorCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PasosResponsablesConsultaTSCompletedEventHandler(object sender, PasosResponsablesConsultaTSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PasosResponsablesConsultaTSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PasosResponsablesConsultaTSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591